// Generated by extendr: do not edit by hand

#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#include <R_ext/Visibility.h>

// Declare the wrapper functions generated by extendr
extern SEXP wrap__process_nvdb_wkb(SEXP wkb_geoms, SEXP col_names, SEXP col_data,
                                    SEXP output_path, SEXP simplify_method,
                                    SEXP node_id_start, SEXP way_id_start);

static const R_CallMethodDef CallEntries[] = {
    {"wrap__process_nvdb_wkb", (DL_FUNC) &wrap__process_nvdb_wkb, 7},
    {NULL, NULL, 0}
};

void attribute_visible R_init_nvdb2osmr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    R_forceSymbols(dll, TRUE);
}
